### PR TITLE
CLI support

### LINKED ISSUE #15: Feature request: CLI support
I understand that this is primarily for Rufus, but I'm in need of being able to directly download the appropriate ISOs from a command line to aid in command-line based Win10 upgrades on the active device. The CLI syntax should require the answers to each selection as an argument, or even assume the values for the current installation with optional overrides. 

Something like:

`powershell -ExecutionPolicy bypass .\Fido.ps1 -version 10 -release "20H1" -edition "home/pro" -locale "en-US" -architecture "x64"`

`powershell -ExecutionPolicy bypass .\Fido.ps1 -assumecurrent -release "1909" `

### PR DESCRIPTION
**Pull request by flx5**
Implement CLI support.
The signature needs to be updated. 
This should fix #15.

### CODE REVIEW

**Comment by pbatard** [comment]
Thanks for the Pull Request. I've actually spotted your changes before you created the PR and had been working on integrating them. I'm going to split the first commit into 2, so that we can have a first part that moves the switch code into individual functions, and the second part that adds CLI support.

As you should see, I have already pushed that first commit as f70836e6c1f2dcc4bdf1e22fac76b01a0bba20cc. And while I credited this one to myself, the subsequent commits willbe credited to you.

I am also going to modify your proposal so that one can use something like `.\Fido.ps1 -Win 10 -Rel 21H1 -Ed Pro -Lang Fr -Arch x64` and get CLI usage automatically detected as well as the relevant `Win10_21H1_French_x64.iso` download.

I've pretty much gotten it sorted out already, but there are still a few things I need to finalize:
```
PS C:\Projects\Fido> .\Fido.ps1 -Win 10 -Rel 21H1 -Ed Pro -Lang Fr -Arch x64
Selected Windows 10
Selected □21H1 (Build 19043.985 - 2021.05)‎□
Selected Windows 10 Home/Pro
Querying https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,Windows10ISO&query=&action=getskuinformationbyproductedition&sessionId=84e5dc39-cbe5-4b71-ae0a-ad6017ba99ca&productEditionId=2033&sdVersion=2
Selected French
Querying https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a224afab-2097-4dfa-a2ba-463eb191a285&host=www.microsoft.com&segments=software-download,Windows10ISO&query=&action=GetProductDownloadLinksBySku&sessionId=84e5dc39-cbe5-4b71-ae0a-ad6017ba99ca&skuId=12741&language=French&sdVersion=2
Selected x64
Download Link: https://software-download.microsoft.com/db/Win10_21H1_French_x64.iso?t=ec5c4112-7659-4bf7-b99b-d3a538843f00&e=1628369761&h=96bf973cd95290a2976f4a9505860d4c
```

**Comment by flx5** [comment]
> Thanks for the Pull Request. I've actually spotted your changes before you created the PR and had been working on integrating them. I'm going to split the first commit into 2, so that we can have a first part that moves the switch code into individual functions, and the second part that adds CLI support.

That actually makes more sense. My commit does it in one because I had to test my changes on the command line.

> I am also going to modify your proposal so that one can use something like `.\Fido.ps1 -Win 10 -Rel 21H1 -Ed Pro -Lang Fr -Arch x64` and get CLI usage automatically detected as well as the relevant `Win10_21H1_French_x64.iso` download.

That looks a lot more usable than my naming. I was just happy to get it to work because I've never had to write Powershell scripts until now.

Just wondering: Would it be possible to have some kind of quiet mode that outputs only the url for piping?

My use case would be to run this script on Linux and pass the download to a tool like wget because the powershell download seems quite slow (although I don't have any numbers to back that claim up):
`powershell -ExecutionPolicy bypass .\Fido.ps1  -Win 10 -Rel 21H1 -Ed Pro -Lang Fr -Arch x64 | xargs wget`

**Comment by pbatard** [comment]
> Just wondering: Would it be possible to have some kind of quiet mode that outputs only the url for piping?

Way ahead of you... :smile:

I also added a `-Silent` option that does just what you ask, as I reckon some people will indeed want to use it that way:

```
PS C:\Projects\Fido> .\Fido.ps1 -Win 10 -Rel 21H1 -Ed Edu -Lang Int -Arch x86 -Silent
https://software-download.microsoft.com/db/Win10_Edu_21H1_EnglishInternational_x32.iso?t=1a260156-b179-4ad1-a8bb-dee1a00cb9d5&e=1628419130&h=922bd1707fda8967e2e704504abd7d27
```

Note that I am however planning to drop the hash function, because I'm not entirely convinced it belongs in a script that's focused on getting a download. My issue is that, if you start to add corollary features such as hash validation to the script, soon enough people start asking for more, and you deviate from the usual commandline philosophy of doing one task only and concentrating on doing it well, instead of multiplying tasks.

I may of course revise this if I see an actual demand for hash validation...

**Comment by flx5** [comment]
> Note that I am however planning to drop the hash function, because I'm not entirely convinced it belongs in a script that's focused on getting a download. My issue is that, if you start to add corollary features such as hash validation to the script, soon enough people start asking for more, and you deviate from the usual commandline philosophy of doing one task only and concentrating on doing it well, instead of multiplying tasks.
> 
> I may of course revise this if I see an actual demand for hash validation...

You might be right about that. Still it would be nice to have the possibility to print the link and the checksum (perhaps tab seperated?). Those ISOs are big files and it would be great to have the ability to check them after the download (with an external tool) to make sure they are not corrupted.

**Comment by pbatard** [comment]
I believe I have finalized commandline support, so I will close this issue.
Eventually, I chose to go with `-GetUrl` instead of `-Silent` for the quiet mode.
Note that I am also planning to apply the BITS patch later on, even though I will be closing this PR, as I want to test that change for regressions a bit more (if I forget to do that, don't hesitate to remind me).

**HOWEVER**, just as I was applying the finishing touches, I found that all my requests to get the Arch download links from the MS servers started to fail, and this even when using the 1.20 release version of the script through Rufus.

And because downloads from the official page still work, through a browser with a non Windows 10 `UserAgent`, and I am also seeing a similar direct URL query download issues from a remote server, I am starting to get very worried that, through a stroke of bad luck, Microsoft have been securing their download page against script requests right at the time when were were finalizing these changes, in which case they might effectively have rendered Fido useless and all this effort utterly pointless.

I am therefore very anxious to find out if I am being paranoid, or if Microsoft has suddenly taken a hostile stance against Fido (which I guess I'll get confirmation sooner rather than later, if Rufus users suddenly find that the Windows ISO download feature has stopped working). Thus, if someone could test either the latest version of the script, or the version that can be downloaded at https://github.com/pbatard/Fido/releases/tag/v1.20 and confirm that it does works for you, I would greatly appreciate it...

**Comment by pbatard** [comment]
Nevermind, looks like I was paranoid.

After rebooting my dev machine, Fido download requests are working again... Pfew!

**Comment by sethbrasile** [comment]
You guys have no idea how great this is! Thank you so much for this! I was just getting to work on implementing basically the same modifications today, only to find that you did exactly what I need 6 days ago. 🍺 for @flx5 and 🍺 for @pbatard!

@wmmatt ^

**Comment by pbatard** [comment]
Happy to hear you like it. For the record I just finalized commandline support with release 1.21 (where I added a couple improvements such as displaying the size of the ISO before download).

Also, with regards to using `System.Net.WebClient` form the BITS patch, I don't think I will do that since `Invoke-Webrequest` works fine and it has the advantage of handling <kbd>Ctrl</kbd>-<kbd>C</kbd> as well as displaying some download progress when invoked from the commandline.

**Pull request closed without merging**
